In [1]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from scipy.misc import imread
import cv2
import os
from sklearn.naive_bayes import GaussianNB

In [2]:
#im = Image.open('full_duck.jpg')
#pix = im.load()
#width = im.size[0]
#height = im.size[1]
#for x in range(width):
#    for y in range(height):
#        r, g, b = pix[x, y]

In [3]:
for ducks in os.listdir(r'duck'):
    print(ducks)

duck01.jpg
duck02.jpg
duck03.jpg
duck04.jpg
duck05.jpg
duck06.jpg
duck07.jpg
duck08.jpg
duck09.jpg
duck10.jpg
duck11.jpg
duck12.jpg
duck13.jpg


In [4]:
for ducks in os.listdir(r'duck'):
    duck = cv2.imread(ducks, cv2.IMREAD_COLOR)
    #print(duck)
    #duck = Image.open(ducks)
    width = duck.shape[0]
    height = duck.shape[1]
    #duck = duck.convert('RGB')
    duckarray = []
    ducklabel=[]
    #print(duck)
    for x in range(width):
        for y in range(height):
            duckarray.append(duck[x,y])
            ducklabel.append(1)
            #print(duck)
            #print(duckarray)
#print (np.mean(duckarray))
#print (np.cov(duckarray))
#print(duckarray)

In [5]:
for unducks in os.listdir(r'unduck'):
    unduck = cv2.imread(unducks, cv2.IMREAD_COLOR)
    #unduck = Image.open(unducks)
    width = unduck.shape[0]
    height = unduck.shape[1]
    #unduck = unduck.convert('RGB')
    unduckarray = []
    unducklabel=[]
    #print(unduck)
    for x in range(width):
        for y in range(height):
            unduckarray.append(unduck[x,y])
            unducklabel.append(0)

In [6]:
print(duckarray)

[array([254, 249, 240], dtype=uint8), array([255, 251, 242], dtype=uint8), array([255, 252, 241], dtype=uint8), array([255, 251, 240], dtype=uint8), array([254, 251, 237], dtype=uint8), array([253, 250, 236], dtype=uint8), array([250, 247, 233], dtype=uint8), array([245, 242, 228], dtype=uint8), array([240, 237, 223], dtype=uint8), array([242, 239, 225], dtype=uint8), array([255, 249, 236], dtype=uint8), array([255, 251, 238], dtype=uint8), array([232, 226, 215], dtype=uint8), array([237, 231, 220], dtype=uint8), array([241, 234, 225], dtype=uint8), array([255, 252, 243], dtype=uint8), array([255, 252, 243], dtype=uint8), array([255, 253, 242], dtype=uint8), array([255, 251, 240], dtype=uint8), array([254, 251, 237], dtype=uint8), array([254, 251, 237], dtype=uint8), array([251, 248, 234], dtype=uint8), array([247, 244, 230], dtype=uint8), array([241, 238, 224], dtype=uint8), array([245, 242, 228], dtype=uint8), array([255, 249, 236], dtype=uint8), array([255, 253, 240], dtype=uint8), 

In [7]:
print(ducklabel)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [8]:
print(unduckarray)

[array([205, 184, 153], dtype=uint8), array([203, 182, 151], dtype=uint8), array([202, 181, 150], dtype=uint8), array([204, 183, 152], dtype=uint8), array([205, 184, 153], dtype=uint8), array([205, 184, 153], dtype=uint8), array([204, 183, 152], dtype=uint8), array([204, 183, 152], dtype=uint8), array([206, 185, 154], dtype=uint8), array([204, 183, 152], dtype=uint8), array([206, 185, 154], dtype=uint8), array([205, 184, 153], dtype=uint8), array([201, 180, 149], dtype=uint8), array([200, 179, 148], dtype=uint8), array([195, 174, 143], dtype=uint8), array([185, 164, 133], dtype=uint8), array([187, 161, 131], dtype=uint8), array([185, 159, 129], dtype=uint8), array([180, 156, 126], dtype=uint8), array([183, 159, 129], dtype=uint8), array([192, 168, 138], dtype=uint8), array([199, 175, 145], dtype=uint8), array([200, 176, 146], dtype=uint8), array([201, 177, 147], dtype=uint8), array([204, 180, 150], dtype=uint8), array([203, 179, 149], dtype=uint8), array([204, 180, 150], dtype=uint8), 

In [9]:
print(unducklabel)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [10]:
duckarray += unduckarray
ducklabel += unducklabel

In [11]:
duckarray = np.array(duckarray)
ducklabel = np.array(ducklabel)

In [12]:
print(duckarray)

[[254 249 240]
 [255 251 242]
 [255 252 241]
 ...
 [135 138 112]
 [135 138 112]
 [134 137 111]]


In [13]:
print(ducklabel)

[1 1 1 ... 0 0 0]


In [14]:
GNB = GaussianNB()
GNB.fit(duckarray, ducklabel)

GaussianNB(priors=None)

In [15]:
findduck = cv2.imread('full_duck.jpg', cv2.IMREAD_COLOR)
width = findduck.shape[0]
height = findduck.shape[1]
for x in range(width):
        data=[]
        
        for y in range(height) :
            data.append(findduck[x,y])

        data = np.array(data)
        predict = GNB.predict(data)
            
        for y in range(height) :
            if(predict[y]==1):
                findduck[x,y]=0,0,255

In [16]:
cv2.imwrite("findducks.jpg",findduck)

True

In [17]:
#full_duck = Image.open('full_duck.jpg')
#width = full_duck.size[0]
#height = full_duck.size[1]
#full_duck = full_duck.convert('RGB')
#fullduckarray = []
#for x in range(width):
#    for y in range(height):
#        r, g, b = full_duck.getpixel((x,y))
#        rgb = (r, g, b)
        #print (np.cov(rgb))
        #fullduckarray.append(rgb)

In [18]:
#testimge1=cv2.imread('duck02.png')
#print(testimge1.shape)

In [19]:
#testimge2=cv2.imread('unduck02.png')
#print(testimge2.shape)

In [20]:
#for duck in os.listdir(r'duck'):
#    print(duck)
#    ducks=cv2.imread(duck)
#    print(ducks.shape)

In [21]:
#for unduck in os.listdir(r'unduck'):
#    print(unduck)
#    noducks=cv2.imread(unduck)
#    print(noducks.shape)

In [ ]:
# 